{% set name = "conda-gitenv" %}
{% set version = "0.4.0" %}
{% set sha = "4540184e41a1c02b1fea53235f365b7d87ff82a8e8c1640251170ab27a4b5ee1" %}

package:
  name: {{ name }} 
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/SciTools/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha }} 

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python
  entry_points:
    - conda-gitenv = conda_gitenv.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - gitpython
    - pyyaml
    - conda 4.3.*
    - conda-build-all
    - conda-build

test:
  requires:
    - git
  imports:
    - conda_gitenv
  commands:
    - conda gitenv --help
    - conda gitenv resolve --help
    - conda gitenv autotag --help
    - conda gitenv autolabel --help
    - conda gitenv deploy --help

about:
  home: https://github.com/SciTools/{{ name }}
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Track environment specifications using a git repo.'

extra:
  recipe-maintainers:
    - pelson
    - bjlittle
    - lbdreyer
