{% set name = "conda-gitenv" %}
{% set version = "0.4.0" %}
{% set sha = "baa170ef677381612d49e5156aa147d16c03148604b3894629267a49360739a7" %}

package:
  name: {{ name }} 
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/SciTools/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha }} 

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python
  entry_points:
    - conda-gitenv = conda_gitenv.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - gitpython
    - pyyaml
    - conda
    - conda-build-all
    - conda-build

test:
  imports:
    - conda_gitenv
  commands:
    - conda gitenv --help
    - conda gitenv resolve --help
    - conda gitenv autotag --help
    - conda gitenv autolabel --help
    - conda gitenv deploy --help

about:
  home: https://github.com/SciTools/{{ name }}
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Track environment specifications using a git repo.'

extra:
  recipe-maintainers:
    - pelson
    - bjlittle
    - lbdreyer
