travis:
  secure:
    BINSTAR_TOKEN: WzUDrFzCMh5LDviAFvXUAdgqs/b9ZIjGFe7v1/FDXV8c1/zWJZLvDP3i/LrFOdQr0W2GRkIlAMhdKxB6lt35sZSn3Rw025caL7mKNCBY9aLT/Yuj1wZkgc8CU0WgUqi11CzGlz+13VdV0BNqN31aWZzdV5LPMxEasNJEuntTd8vPp/BkSh2yPu/OJzTYGfTglpFlV6qqyWrUHgfPsNbjXQACKxvIe7kl1qR15hwkD3VasuwbjW5XJKICyIucX5XAsKABOoA2Tn4ghY34pWytrIwmTX3E4JXnTzh05oX44Ue+kxVTbGvV7CYv+Z/olh65IqTRx3DWbAUwmjFQye+mK5/IpRMxarx7JApkRI3Qvyq8tO0xcWWKHPrJXUZauIOLDGQJ9JS7Gclho/ry8Gw1JR9c80Pzk7ttFfU/8/3pAC4BPrymC3N/LkJUi/oPj/MaA7sNhilpkmJgxKut2bopL2FnOI7rXUBWwj2EgoUwIbeWUVJkE9UYoOS8DHAXYDxjI2fN5LI243BSCReIhn9S+8d3JwTWWRUU+ymai9qj3fbplb6NqAYKrJTOw+WduJvgSz6GKQ93Xjh2lXygqQMLyfZehm+yv0JrrHcaGyPGWpXD3AKf4jLKeSl4xmkW76jXpZN5d+jDVd3WR9TMPI3YDW3Fuqw9grC1KcMnaepbrxw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
